入力値チェックの実装
KyoichiroTomatsu-R/ex-emp-management-bugfix pull request #2
Opened 2021-06-07 06:49 UTC by KyoichiroTomatsu-R

入力値チェックを実装しました。
多分feature/screenTransitionのブランチの中にこのブランチを作成してしまいました。以後気を付けます

2021-06-07 08:17 UTC, tomoki-rks reviewed
勝手にレビューできるのかテスト

2021-06-07 08:17 UTC, tomoki-rks commented on src/main/java/jp/co/sample/emp_management/form/InsertAdministratorForm.java
> +	@NotBlank
エラーメッセージが埋め込まれていないようです

2021-06-07 08:17 UTC, KyoichiroTomatsu-R commented on src/main/java/jp/co/sample/emp_management/form/InsertAdministratorForm.java
> +	@NotBlank
なきゃダメなんですか？

2021-06-07 08:18 UTC, tomoki-rks commented on src/main/java/jp/co/sample/emp_management/form/InsertAdministratorForm.java
> +	@NotBlank
さあ……？

2021-06-07 08:35 UTC, igamasayuki requested changes
修正いただきたい部分をコメントで残しているため修正後再度レビュー依頼をお願いします。

2021-06-07 08:35 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/form/InsertAdministratorForm.java
> +	@NotBlank
エラーメッセージ埋め込まれていない場合、エラーは英語で出ませんか？
もしそうなら日本語で対応しましょう！

2021-06-07 08:48 UTC, KyoichiroTomatsu-R commented on src/main/java/jp/co/sample/emp_management/form/InsertAdministratorForm.java
> +	@NotBlank
![image](https://user-images.githubusercontent.com/84486212/120987447-8f7a5100-c7b8-11eb-9aad-a3069b93da91.png)
一応デフォルトでエラーメッセージが出ますが実装致します

2021-06-08 02:07 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2021-06-08 02:07 UTC, merged